"""init db

Revision ID: 9912396391c9
Revises: 
Create Date: 2020-08-02 01:10:17.388059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9912396391c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    genre_table = op.create_table('genres',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_external_id'), 'genres', ['external_id'], unique=False)
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_table('movies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('external_id', sa.Integer(), nullable=False),
        sa.Column('popularity', sa.Float(), nullable=True),
        sa.Column('vote_count', sa.Integer(), nullable=True),
        sa.Column('video', sa.Boolean(), nullable=True),
        sa.Column('poster_path', sa.String(), nullable=True),
        sa.Column('adult', sa.Boolean(), nullable=True),
        sa.Column('backdrop_path', sa.String(), nullable=True),
        sa.Column('original_language', sa.String(), nullable=True),
        sa.Column('original_title', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('vote_average', sa.Float(), nullable=True),
        sa.Column('overview', sa.String(), nullable=True),
        sa.Column('release_date', sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_external_id'), 'movies', ['external_id'], unique=False)
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    op.create_table('movie_genres',
        sa.Column('movie_id', sa.Integer(), nullable=True),
        sa.Column('genre_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
        sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], )
    )

    # All the movie genres from the Movie DB API.
    op.bulk_insert(
        genre_table,
        [
            {
                "external_id": 28,
                "name": "Action"
            },
            {
                "external_id": 12,
                "name": "Adventure"
            },
            {
                "external_id": 16,
                "name": "Animation"
            },
            {
                "external_id": 35,
                "name": "Comedy"
            },
            {
                "external_id": 80,
                "name": "Crime"
            },
            {
                "external_id": 99,
                "name": "Documentary"
            },
            {
                "external_id": 18,
                "name": "Drama"
            },
            {
                "external_id": 10751,
                "name": "Family"
            },
            {
                "external_id": 14,
                "name": "Fantasy"
            },
            {
                "external_id": 36,
                "name": "History"
            },
            {
                "external_id": 27,
                "name": "Horror"
            },
            {
                "external_id": 10402,
                "name": "Music"
            },
            {
                "external_id": 9648,
                "name": "Mystery"
            },
            {
                "external_id": 10749,
                "name": "Romance"
            },
            {
                "external_id": 878,
                "name": "Science Fiction"
            },
            {
                "external_id": 10770,
                "name": "TV Movie"
            },
            {
                "external_id": 53,
                "name": "Thriller"
            },
            {
                "external_id": 10752,
                "name": "War"
            },
            {
                "external_id": 37,
                "name": "Western"
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_genres')
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_external_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_index(op.f('ix_genres_external_id'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
